apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sime.fullname" . }}-config
  labels:
    {{- include "sime.labels" . | nindent 4 }}
data:
  SIME_PORT: "3000"
  SIME_ASSET_ROOT: /app/assets
  SIME_PG_HOST: {{ .Values.postgres.host | quote }}
  SIME_PG_PORT: {{ .Values.postgres.port | quote }}
  SIME_PG_USER: {{ .Values.postgres.user | quote }}
  SIME_PG_DB: {{ .Values.postgres.database | quote }}
  SIME_PG_DDL_DIR: /app/assets/storage/pg/init
  SIME_LAKE_DIR: /app/data/lake
  {{- if .Values.mqtt.enabled }}
  SIME_MQTT_URL: {{ .Values.mqtt.url | quote }}
  {{- end }}
