apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sime.fullname" . }}-lake
  labels:
    {{- include "sime.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.lake.persistence.size }}
---
{{- if not .Values.postgres.external }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sime.fullname" . }}-pg
  labels:
    {{- include "sime.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}
