apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sime.fullname" . }}-secret
  labels:
    {{- include "sime.labels" . | nindent 4 }}
type: Opaque
stringData:
  pg-password: {{ .Values.postgres.password | quote }}
  admin-password: {{ .Values.auth.adminPassword | quote }}
  auth-secret: {{ .Values.auth.jwtSecret | default (randAlphaNum 32) | quote }}
